services:
 catalogdb:
  image: postgres

 basketdb:
  image: postgres

 distributedcache:
  image: redis

 orderdb:
  image: mcr.microsoft.com/mssql/server

 messagebroker:
  image: rabbitmq:management

 catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

 basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

 discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
 ordening.api:
    image: ${DOCKER_REGISTRY-}ordeningapi
    build:
      context: .
      dockerfile: Services/Ordening/Ordening.API/Dockerfile

 yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

 shopping.web:
    image: ${DOCKER_REGISTRY-}shoppingweb
    build:
      context: .
      dockerfile: WebApps/Shopping.Web/Dockerfile

volumes:
 postgres_catalog:
 postgres_basket: